title: The Thoughts of a Poindexter
description: Articles about topics that interest me as I progress through my career as a Back End Engineer 
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
