title: Thoughts of a Poindexter
description: Articles about topics that interest me as I progress through my career as a Back End Engineer 
show_downloads: false
theme: jekyll-theme-architect
# Google Analytics
google_analytics: UA-112027672-1